"""
ApexSpreadator — Data Models
All dataclasses and enums representing options contracts, spreads, market structure zones, and trade state.
"""
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional, List, Dict, Any


class TradeStatus(Enum):
    """Status of a trade."""
    PENDING = "pending"
    OPEN = "open"
    CLOSING = "closing"
    CLOSED = "closed"
    CANCELLED = "cancelled"
    ERROR = "error"


class ExitReason(Enum):
    """Why a position was closed."""
    PROFIT_TARGET = "profit_target"
    STOP_LOSS = "stop_loss"
    TIME_EXIT = "time_exit"
    MANUAL_CLOSE = "manual_close"
    CIRCUIT_BREAKER = "circuit_breaker"


class AgentState(Enum):
    """Agent operational state."""
    STARTING = "starting"
    RUNNING = "running"
    PAUSED = "paused"
    STOPPED = "stopped"
    ERROR = "error"


@dataclass
class OptionLeg:
    """A single option contract leg."""
    con_id: int = 0
    symbol: str = ""
    expiration: str = ""       # YYYYMMDD format
    strike: float = 0.0
    right: str = "C"           # C or P
    action: str = ""           # BUY or SELL
    quantity: int = 0
    # Market data
    bid: float = 0.0
    ask: float = 0.0
    mid: float = 0.0
    last: float = 0.0
    iv: float = 0.0
    # Greeks
    delta: float = 0.0
    gamma: float = 0.0
    theta: float = 0.0
    vega: float = 0.0
    dte: int = 0

    @property
    def description(self) -> str:
        return f"{self.symbol} {self.expiration} {self.strike}{self.right} {self.action}"


@dataclass
class VerticalSpread:
    """A vertical spread consisting of a long option leg and a short option leg."""
    id: str = ""
    symbol: str = ""
    expiration: str = ""
    right: str = "C"            # C for Call spread, P for Put spread
    long_leg: Optional[OptionLeg] = None
    short_leg: Optional[OptionLeg] = None
    quantity: int = 0

    # Pricing
    net_debit: float = 0.0      # Premium paid to open
    current_value: float = 0.0   # Current market price of the spread

    # Risk telemetry
    risk: float = 0.0           # Max Risk = Net Debit
    reward: float = 0.0         # Max Reward = Width - Net Debit
    rr_ratio: float = 0.0       # Reward/Risk ratio (must be >= 2.5)

    @property
    def width(self) -> float:
        if self.long_leg and self.short_leg:
            return abs(self.long_leg.strike - self.short_leg.strike)
        return 0.0

    @property
    def unrealized_pnl(self) -> float:
        return (self.current_value - self.net_debit) * self.quantity * 100.0

    @property
    def unrealized_pnl_pct(self) -> float:
        if self.net_debit == 0:
            return 0.0
        return (self.current_value - self.net_debit) / self.net_debit

    @property
    def description(self) -> str:
        long_stk = self.long_leg.strike if self.long_leg else 0.0
        short_stk = self.short_leg.strike if self.short_leg else 0.0
        spread_type = "Bull Call" if self.right == "C" else "Bear Put"
        return f"{self.symbol} {self.expiration} {long_stk}/{short_stk} {spread_type} Spread"


@dataclass
class Zone:
    """A supply or demand zone formed by price action consolidation."""
    id: str = ""
    type: str = ""              # "DEMAND" or "SUPPLY"
    high: float = 0.0
    low: float = 0.0
    origin_candle_time: str = ""
    is_active: bool = True

    @property
    def description(self) -> str:
        return f"{self.type} Zone ({self.low:.2f} - {self.high:.2f})"


@dataclass
class Opportunity:
    """A trade signal generated by a zone retest that passed the R:R filter."""
    symbol: str = ""
    zone: Optional[Zone] = None
    direction: str = ""         # "BULLISH" or "BEARISH"
    underlying_price: float = 0.0
    spread: Optional[VerticalSpread] = None
    score: float = 85.0         # Compatibility score
    timestamp: str = ""
    is_actionable: bool = True
    invalidation_price: float = 0.0


@dataclass
class Position:
    """An active vertical spread position."""
    id: str = ""
    spread: Optional[VerticalSpread] = None
    status: TradeStatus = TradeStatus.PENDING
    entry_time: str = ""
    entry_price: float = 0.0
    quantity: int = 0
    # Live tracking
    current_value: float = 0.0
    unrealized_pnl: float = 0.0
    unrealized_pnl_pct: float = 0.0
    # Underlying price levels
    underlying_price_at_entry: float = 0.0
    take_profit_price: float = 0.0    # Sold strike price level
    invalidation_price: float = 0.0   # Stop loss level (past the zone boundary)
    # Order tracking
    entry_order_id: int = 0
    exit_order_id: int = 0

    @property
    def total_risk(self) -> float:
        return self.entry_price * self.quantity * 100.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "symbol": self.spread.symbol if self.spread else "",
            "long_strike": self.spread.long_leg.strike if (self.spread and self.spread.long_leg) else 0.0,
            "short_strike": self.spread.short_leg.strike if (self.spread and self.spread.short_leg) else 0.0,
            "right": self.spread.right if self.spread else "C",
            "expiration": self.spread.expiration if self.spread else "",
            "status": self.status.value,
            "entry_time": self.entry_time,
            "entry_price": self.entry_price,
            "quantity": self.quantity,
            "current_value": self.current_value,
            "unrealized_pnl": self.unrealized_pnl,
            "unrealized_pnl_pct": self.unrealized_pnl_pct,
            "underlying_price_at_entry": self.underlying_price_at_entry,
            "take_profit_price": self.take_profit_price,
            "invalidation_price": self.invalidation_price,
            "front_dte": self.spread.long_leg.dte if (self.spread and self.spread.long_leg) else 0,
        }


@dataclass
class TradeRecord:
    """A completed trade record."""
    id: str = ""
    symbol: str = ""
    long_strike: float = 0.0
    short_strike: float = 0.0
    right: str = "C"
    expiration: str = ""
    quantity: int = 0
    # Entry
    entry_time: str = ""
    entry_price: float = 0.0
    underlying_price_at_entry: float = 0.0
    # Exit
    exit_time: str = ""
    exit_price: float = 0.0
    underlying_price_at_exit: float = 0.0
    exit_reason: str = ""
    # P&L
    realized_pnl: float = 0.0
    realized_pnl_pct: float = 0.0
    holding_days: int = 0
    # Analysis
    agent_analysis: str = ""
    lessons_learned: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "symbol": self.symbol,
            "long_strike": self.long_strike,
            "short_strike": self.short_strike,
            "right": self.right,
            "expiration": self.expiration,
            "quantity": self.quantity,
            "entry_time": self.entry_time,
            "entry_price": self.entry_price,
            "underlying_price_at_entry": self.underlying_price_at_entry,
            "exit_time": self.exit_time,
            "exit_price": self.exit_price,
            "underlying_price_at_exit": self.underlying_price_at_exit,
            "exit_reason": self.exit_reason,
            "realized_pnl": self.realized_pnl,
            "realized_pnl_pct": self.realized_pnl_pct,
            "holding_days": self.holding_days,
            "agent_analysis": self.agent_analysis,
            "lessons_learned": self.lessons_learned,
        }


@dataclass
class AccountSnapshot:
    """Current account state."""
    balance: float = 0.0
    equity: float = 0.0
    buying_power: float = 0.0
    daily_pnl: float = 0.0
    monthly_pnl: float = 0.0
    total_pnl: float = 0.0
    open_positions_count: int = 0
    total_risk_exposure: float = 0.0
    # Performance
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    win_rate: float = 0.0
    avg_win: float = 0.0
    avg_loss: float = 0.0
    profit_factor: float = 0.0
    month_start_balance: float = 0.0
    monthly_target: float = 0.0
    monthly_progress_pct: float = 0.0
    trading_days_remaining: int = 0
    timestamp: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "balance": self.balance,
            "equity": self.equity,
            "buying_power": self.buying_power,
            "daily_pnl": self.daily_pnl,
            "monthly_pnl": self.monthly_pnl,
            "total_pnl": self.total_pnl,
            "open_positions_count": self.open_positions_count,
            "total_risk_exposure": self.total_risk_exposure,
            "total_trades": self.total_trades,
            "winning_trades": self.winning_trades,
            "losing_trades": self.losing_trades,
            "win_rate": self.win_rate,
            "avg_win": self.avg_win,
            "avg_loss": self.avg_loss,
            "profit_factor": self.profit_factor,
            "month_start_balance": self.month_start_balance,
            "monthly_target": self.monthly_target,
            "monthly_progress_pct": self.monthly_progress_pct,
            "trading_days_remaining": self.trading_days_remaining,
            "timestamp": self.timestamp,
        }


@dataclass
class ScannerStatus:
    """Status of the opportunity scanner."""
    is_scanning: bool = False
    last_scan_time: str = ""
    next_scan_time: str = ""
    opportunities_found: int = 0
    best_opportunity: Optional[Dict[str, Any]] = None
    seconds_until_next: int = 0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "is_scanning": self.is_scanning,
            "last_scan_time": self.last_scan_time,
            "next_scan_time": self.next_scan_time,
            "opportunities_found": self.opportunities_found,
            "best_opportunity": self.best_opportunity,
            "seconds_until_next": self.seconds_until_next,
        }


@dataclass
class JournalEntry:
    """A trade journal entry."""
    id: str = ""
    timestamp: str = ""
    trade_id: str = ""
    entry_type: str = ""        # "entry", "exit", "analysis", "lesson", "weekly_summary"
    symbol: str = ""
    content: str = ""
    data: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "timestamp": self.timestamp,
            "trade_id": self.trade_id,
            "entry_type": self.entry_type,
            "symbol": self.symbol,
            "content": self.content,
            "data": self.data,
        }


@dataclass
class LearningState:
    """State tracking for the learning engine."""
    total_trades_analyzed: int = 0
    underlying_stats: Dict[str, Any] = field(default_factory=dict)
    dte_bucket_stats: Dict[str, Any] = field(default_factory=dict)
    last_adjustment_at_trade: int = 0
    adjusted_entry_threshold: float = 75.0
    adjusted_profit_target: float = 0.5
    adjusted_stop_loss: float = 0.5
    adjustment_history: List[Dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "total_trades_analyzed": self.total_trades_analyzed,
            "underlying_stats": self.underlying_stats,
            "dte_bucket_stats": self.dte_bucket_stats,
            "last_adjustment_at_trade": self.last_adjustment_at_trade,
            "adjusted_entry_threshold": self.adjusted_entry_threshold,
            "adjusted_profit_target": self.adjusted_profit_target,
            "adjusted_stop_loss": self.adjusted_stop_loss,
            "adjustment_history": self.adjustment_history,
        }
